crud/urls.py
from django.urls import path
from . import views

app_name = 'crud'

urlpatterns = [
    path('', views.index, name='index'),
    path('laptops', views.display_laptop, name='laptops'),
    path('desktops', views.display_desktop, name='desktops'),
    path('mobiles', views.display_mobile, name='mobiles'),

    path('add_laptop', views.add_laptop, name='add_laptop'),
    path('add_desktop', views.add_desktop, name='add_desktop'),
    path('add_mobile', views.add_mobile, name='add_mobile'),

    path('del_laptop/<int:pk>', views.del_laptop, name='del_laptop'),
    path('del_desktop/<int:pk>', views.del_desktop, name='del_desktop'),
    path('del_mobile/<int:pk>', views.del_mobile, name='del_mobile'),

    path('edit_laptop/<int:pk>', views.edit_laptop, name='edit_laptop'),
    path('edit_desktop/<int:pk>', views.edit_desktop, name='edit_desktop'),
    path('edit_mobile/<int:pk>', views.edit_mobile, name='edit_mobile'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('crud.urls')),
    path('admin/', admin.site.urls),
]

crud/models.py
from django.db import models

# Create your models here.


class Device(models.Model):
    choices = (
        ('AVAILIBLE', 'Ready to be purchased'),
        ('SOLD', 'Sold'),
        ('RESTOCKING', 'Restocking in few days'),
    )

    type = models.CharField(max_length=100, blank=False)
    price = models.IntegerField()
    status = models.CharField(max_length=10, choices=choices, default='SOLD')
    issues = models.CharField(max_length=100, default='No issues')

    class Meta:
        abstract = True

    def __str__(self):
        return 'Type: {}, Price: {}'.format(self.type, self.price)


class Laptop(Device):
    pass


class Desktop(Device):
    pass


class Mobile(Device):
    pass

crud/forms.py
from django.forms import ModelForm
from django import  forms
from .models import *


class LaptopForm(ModelForm):
    class Meta:
        model = Laptop
        fields = '__all__'
        widgets  = {
            'type': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'price': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'status': forms.Select(
                attrs={
                    'class':'form-control form-control-sm'
                }
            ),
            'issues': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
        }


class DesktopForm(ModelForm):
    class Meta:
        model = Desktop
        fields = '__all__'
        widgets  = {
            'type': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'price': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'status': forms.Select(
                attrs={
                    'class':'form-control form-control-sm'
                }
            ),
            'issues': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
        }


class MobileForm(ModelForm):
    class Meta:
        model = Mobile
        fields = '__all__'
        widgets  = {
            'type': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'price': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'status': forms.Select(
                attrs={
                    'class':'form-control form-control-sm'
                }
            ),
            'issues': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
        }

crud/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import Desktop, Laptop, Mobile
from .forms import DesktopForm, LaptopForm, MobileForm


# Create your views here.
def index(request):
    context = {
        'header': ''
    }
    return render(request, 'index.html', context)


# DISPLAY
def display_laptop(request):
    items = Laptop.objects.all()
    context = {
        'items': items,
        'header': 'Laptop',
    }
    return render(request, 'index.html', context)


def display_desktop(request):
    items = Desktop.objects.all()
    context = {
        'items': items,
        'header': 'Desktop',
    }
    return render(request, 'index.html', context)


def display_mobile(request):
    items = Mobile.objects.all()
    context = {
        'items': items,
        'header': 'Mobile',
    }
    return render(request, 'index.html', context)


# ADD
def add_device(request, cls):
    if request.method == "POST":
        form = cls(request.POST)
        if form.is_valid():
            form.save()
            url=''
            if cls==LaptopForm:
                url = '/laptops'
            elif cls==DesktopForm:
                url = '/desktops'
            else:
                url = '/mobiles'
            return redirect(url)
    else:
        form = cls()
        context = {
            'form': form
        }
        return render(request, 'form.html', context)


def add_laptop(request):
    return add_device(request, LaptopForm)


def add_desktop(request):
    return add_device(request, DesktopForm)


def add_mobile(request):
    return add_device(request, MobileForm)


# REMOVE
def del_device(request, cls, pk):
    cls.objects.filter(id=pk).delete()
    items = cls.objects.all()
    context = {
        'items': items,
    }

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def del_laptop(request, pk):
    return del_device(request, Laptop, pk)


def del_desktop(request, pk):
    return del_device(request, Desktop, pk)


def del_mobile(request, pk):
    return del_device(request, Mobile, pk)


# Update
def edit_device(request, cls, model, pk):
    obj = get_object_or_404(model, pk=pk)
    if request.method == "POST":
        form = cls(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            url=''
            if model==Laptop:
                url = '/laptops'
            elif model==Desktop:
                url = '/desktops'
            else:
                url = '/mobiles'
            return redirect(url)
    else:
        form = cls(instance=obj)
        context = {
            'form': form,
        }
        return render(request, 'form.html', context)


def edit_laptop(request, pk):
    return edit_device(request, LaptopForm, Laptop, pk)


def edit_desktop(request, pk):
    return edit_device(request, DesktopForm, Desktop, pk)


def edit_mobile(request, pk):
    return edit_device(request, MobileForm, Mobile, pk)

crud/templates/_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    /> 
    {% comment %} <link rel="stylesheet" href={% static '/css/style.css' %}> {% endcomment %}
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div>{% include 'navbar.html' %}</div>
    <br/>
    <div class="container">{% block content %}{% endblock content %}</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

crud/templates/form.html
{% extends '_layout.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {% for field in form %}
                <div class="form-group row">
                    <label for="id_{{ field.name }}" class="col-3 col-form-label">{{ field.label }}</label>
                    <div class="col-9">
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

crud/templates/index.html
{% extends '_layout.html' %}
{% load static %}
{% load humanize %}
{% block content %}
    <div class="button-group" style="margin: auto;">
        <a href="{% url 'crud:laptops' %}" class="btn btn-outline-primary btn-md" role="button">Laptop</a>
        <span>|</span>
        <a href="{% url 'crud:desktops' %}" class="btn btn-outline-primary btn-md" role="button">Desktop</a>
        <span>|</span>
        <a href="{% url 'crud:mobiles' %}" class="btn btn-outline-primary btn-md" role="button">Mobile</a>
        
    </div>

    {% if header == "" %}
        <br>
        <img src="{% static "img/dvd.gif" %}" alt="My image" class="rounded mx-auto d-block" width="840px" height="600px">
    {% else %}
        <br>
        <h4>Current view: {{ header }} 
            {% if header|lower == "laptop" %}
                <a href="{% url 'crud:add_laptop' %}" class="btn btn-outline-secondary btn-sm" role="button">+</a>
            {% elif header|lower == "desktop" %}
                <a href="{% url 'crud:add_desktop' %}" class="btn btn-outline-secondary btn-sm" role="button">+</a>
            {% else %}
                <a href="{% url 'crud:add_mobile' %}" class="btn btn-outline-secondary btn-sm" role="button">+</a>
            {% endif %}
        </h4>
        <br>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Model</th>
                    <th>Price</th>
                    <th>Status</th>
                    <th>Issues</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{item.type}}</td>
                        <td>{{item.price|intcomma}} USD</td>
                        <td>
                            {% if item.status == 'AVAILIBLE'%}
                                <button type="button" class="btn btn-outline-success btn-sm" disabled>{{item.status}}</button>
                            {% elif item.status == 'SOLD' %}
                                <button type="button" class="btn btn-outline-danger btn-sm" disabled>{{item.status}}</button>
                            {% else %}
                                <button type="button" class="btn btn-outline-primary btn-sm" disabled>{{item.status}}</button>
                            {% endif %}
                        </td>
                        <td>{{item.issues}}</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                {% if header|lower == "laptop" %}
                                    <a href="{% url 'crud:edit_laptop' item.id%}" type="button" class="btn btn-warning btn-sm">Edit</a>
                                    <a href="{% url 'crud:del_laptop' item.id %}" type="button" class="btn btn-danger btn-sm">Remove</a>
                                {% elif header|lower == "desktop" %}
                                    <a href="{% url 'crud:edit_desktop' item.id%}" type="button" class="btn btn-warning btn-sm">Edit</a>
                                    <a href="{% url 'crud:del_desktop' item.id %}" type="button" class="btn btn-danger btn-sm">Remove</a>
                                {% else %}
                                    <a href="{% url 'crud:edit_mobile' item.id%}" type="button" class="btn btn-warning btn-sm">Edit</a>
                                    <a href="{% url 'crud:del_mobile' item.id %}" type="button" class="btn btn-danger btn-sm">Remove</a>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock content %}
    

crud/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'crud:index' %}">HTDyu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> 
</nav>